### PR TITLE
[Fix/#286] share qa 반영

### LINKED ISSUE #286: [Fix] Share QA
## 🚩 TO DO
- [ ] QA 수정사항 반영하기..

### PR DESCRIPTION
**Pull request by hyeeum**
## *📌 Issue*
- closed #286

## *⛳️ Work Description*
- qa 사항 반영
  - 구분선 삭제
  - 탑바도 같이 스크롤되게 변경
  - 네비게이션 정리 및 탑바 문구/공유버튼 상태 관리

## *📸 Screenshot*
Before | After
:--: | :--:
 | 
<video src="https://github.com/user-attachments/assets/a7cff0f2-d043-4408-9097-195978c1b14b" width="300" > | <video src="https://github.com/user-attachments/assets/06ac2a0f-fb15-4e7e-8df3-8ba142ed50f9" width="300" >
<video src="https://github.com/user-attachments/assets/8060eb85-e04e-4cfb-8433-1c9117814511" width="300" > | <video src="https://github.com/user-attachments/assets/44fd7285-e2c6-4a34-bce9-f98d618c2b53" width="300" >

## *📢 To Reviewers*
- 오랜만에 올리는 pr 이네요...

## Summary by CodeRabbit

- **New Features**
  - Introduced an enhanced jogbo detail header that dynamically indicates your content status.
  - Improved back navigation across screens, providing a more intuitive return to home or previous views.

- **Refactor**
  - Streamlined share functionality with clearer ownership cues.
  - Refined layout structures on jogbo detail and store screens for consistency.

- **Style**
  - Updated list views by removing horizontal dividers for a cleaner, modern interface.

### CODE REVIEW

File: feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt [hunk 1]
```diff
@@ -193,119 +184,84 @@ fun MyJogboDetailScreen(
...
-                                chips = jogboChips,
-                                userNickname = userNickname,
-                                shareJogboDialogState = {
-                                    val defaultImageUrl = KAKAO_SHARE_DEFAULT_IMAGE
-                                    val imageUrl =
-                                        state.data.firstOrNull { it.imageUrl != null }?.imageUrl
-                                            ?: defaultImageUrl
+                is EmptyUiState.Success -> {
+                    item {
+                        JogboHeader(
```
Comment (chattymin) [inline feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt:213]: 헤더가 같이 움직이는게 기획 명세인가요???
한번만 확인 부탁드릴게요...!!
안움직이는게 훨 나을거 같은딩

**Review by chattymin — APPROVED** [review]
고생했서요~

File: feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt (hunk 1 above)
Comment (hyeeum) [reply feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt:213]: 요거는 디자인측에서 수정해달라고 하셨습니당!
